[build]
  command = "npm run build"
  publish = "dist/fahsi/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# ğŸ” Soporte para rutas Angular (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
