[build]
  command = "npm run build"
  publish = "dist/fahsi/browser"

[[plugins]]
  package = "@netlify/angular-runtime"

# ğŸ”„ RedirecciÃ³n para Single Page Applications (Angular)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
